### ISSUE TITLE
App crashes if users clicks "Cancel" on Facebook login page

### ISSUE THREAD

**Issue by WERUreo** [SD10/Snappy#3]
When testing the app, I clicked the Facebook login button on the login screen.  When I was taken to the Facebook page to log in, I saw that I was already authorized.  When I click "Cancel", the app crashes.

In the log, I get "fatal error: unexpectedly found nil while unwrapping an Optional value"

**Comment by SD10** [comment]
Issue #3 Solved
Check if facebookResult.isCancelled and dismiss view controller
